import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english
    case chinese

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english: "English"
        case .chinese: "中文"
        }
    }
}

enum AppStrings {
    static func text(_ key: String, language: AppLanguage) -> String {
        if language == .chinese, let value = zhCN[key] {
            return value
        }
        return enUS[key] ?? key
    }

    private static let enUS: [String: String] = [
        "about": "About",
        "about.description": "A native macOS SwiftUI controller for OPPO, OnePlus, and realme earbuds, adapted from the Windows OPPO Pods reverse-engineered protocol.",
        "about.license": "License",
        "about.license.body": "The protocol-derived implementation and bundled device metadata are treated as GPL-3.0-derived material from the reference project.",
        "about.reference": "Protocol and device matrix reference",
        "about.reference.body": "Zhaoyi-ya/OPPO-Pods-For-Windows, Leaf-lsgtky/OppoPods, 1812z/OppoPods, and OPPO Melody 16.8.1 extracted device metadata.",
        "about.sync": "Upstream sync",
        "about.sync.body": "Core protocol files intentionally keep upstream command names and packet order so later Windows updates can be ported with smaller diffs.",
        "adaptiveAnc": "Adaptive ANC",
        "anc.level": "ANC level",
        "anc.mode": "ANC mode",
        "anc.unsupported": "This model does not expose ANC controls in the imported device matrix.",
        "autoDetect": "Auto detect",
        "battery": "Battery",
        "bluetoothConnected": "Bluetooth connected",
        "capabilities": "Capabilities",
        "charging": "Charging",
        "commandCompatibility": "Command Compatibility",
        "connect": "Connect",
        "connected": "Connected",
        "connecting": "Connecting",
        "connection": "Connection",
        "controlledByApp": "Connected in OPods",
        "controls": "Controls",
        "detected": "Detected",
        "deviceModel": "Device Model",
        "devices": "Devices",
        "disconnect": "Disconnect",
        "disconnected": "Disconnected",
        "dualDevice": "Dual-device connection",
        "dualDeviceList": "Dual-device List",
        "eqPreset": "EQ preset",
        "gameMode": "Game mode",
        "language": "Language",
        "legacyGameFeature": "Send legacy low-latency game feature too",
        "modelId": "Model ID",
        "needsAttention": "Needs attention",
        "noDeviceList": "No Device List",
        "noPairedDevices": "No Paired Devices",
        "noReport": "No report",
        "noiseControl": "Noise Control",
        "off": "Off",
        "on": "On",
        "overview": "Overview",
        "override": "Override",
        "paired": "Paired",
        "pairedBluetoothDevices": "Paired Bluetooth Devices",
        "pairHint": "Use macOS Bluetooth settings to pair earbuds first.",
        "quit": "Quit",
        "ready": "Ready",
        "refresh": "Refresh",
        "refreshDevices": "Refresh Devices",
        "settings": "Settings",
        "showMainWindow": "Show Main Window",
        "sound": "Sound",
        "spatialAudio": "Spatial audio",
        "spatialAudioModes": "Spatial audio modes",
        "spatialSound": "Spatial sound",
        "switchDevice": "Switch",
        "takeControl": "Take Control",
        "unknown": "Unknown",
        "unsupportedDevice": "Unsupported",
        "wearDetection": "Wear Detection",

        "anc.adaptive": "Adaptive",
        "anc.deep": "Deep",
        "anc.light": "Light",
        "anc.medium": "Medium",
        "anc.off": "Off",
        "anc.smart": "Noise Cancelling",
        "anc.transparency": "Transparency",
        "component.case": "Case",
        "component.left": "Left",
        "component.right": "Right",
        "phase.connected": "Connected",
        "phase.connecting": "Connecting",
        "phase.disconnected": "Disconnected",
        "phase.failed": "Needs attention",
        "spatial.fixed": "Fixed",
        "spatial.off": "Off",
        "spatial.tracking": "Head Tracking",
        "status.disconnected": "Disconnected.",
        "status.initial": "Pair OPPO, OnePlus, or realme earbuds in macOS Bluetooth settings, then connect.",
        "status.searching": "Searching for a supported paired device...",
        "wear.disconnected": "Disconnected",
        "wear.inCase": "In case",
        "wear.removed": "Removed",
        "wear.unknown": "Unknown",
        "wear.worn": "Worn"
    ]

    private static let zhCN: [String: String] = [
        "about": "关于",
        "about.description": "面向 OPPO、OnePlus、realme 耳机的原生 macOS SwiftUI 控制器，基于 Windows 版 OPPO Pods 的逆向协议适配。",
        "about.license": "开源协议",
        "about.license.body": "协议相关实现和随包设备元数据按参考项目的 GPL-3.0 派生材料处理。",
        "about.reference": "协议与设备矩阵来源",
        "about.reference.body": "Zhaoyi-ya/OPPO-Pods-For-Windows、Leaf-lsgtky/OppoPods、1812z/OppoPods，以及从 OPPO 欢律 16.8.1 提取的设备元数据。",
        "about.sync": "上游同步",
        "about.sync.body": "核心协议文件刻意保留上游命令名和包顺序，之后移植 Windows 版更新时可以更小范围对照。",
        "adaptiveAnc": "自适应降噪",
        "anc.level": "降噪深度",
        "anc.mode": "降噪模式",
        "anc.unsupported": "导入的设备矩阵没有声明这个型号支持降噪控制。",
        "autoDetect": "自动检测",
        "battery": "电量",
        "bluetoothConnected": "蓝牙已连接",
        "capabilities": "能力",
        "charging": "充电中",
        "commandCompatibility": "命令兼容性",
        "connect": "连接",
        "connected": "已连接",
        "connecting": "连接中",
        "connection": "连接",
        "controlledByApp": "已由 OPods 接管",
        "controls": "控制",
        "detected": "已识别",
        "deviceModel": "设备型号",
        "devices": "设备",
        "disconnect": "断开",
        "disconnected": "未连接",
        "dualDevice": "双设备连接",
        "dualDeviceList": "双设备列表",
        "eqPreset": "EQ 预设",
        "gameMode": "游戏模式",
        "language": "语言",
        "legacyGameFeature": "同时发送旧版低延迟游戏模式特征",
        "modelId": "型号 ID",
        "needsAttention": "需要处理",
        "noDeviceList": "暂无设备列表",
        "noPairedDevices": "暂无已配对设备",
        "noReport": "暂无上报",
        "noiseControl": "降噪控制",
        "off": "关闭",
        "on": "开启",
        "overview": "概览",
        "override": "手动指定",
        "paired": "已配对",
        "pairedBluetoothDevices": "已配对蓝牙设备",
        "pairHint": "请先在 macOS 蓝牙设置中配对耳机。",
        "quit": "退出",
        "ready": "就绪",
        "refresh": "刷新",
        "refreshDevices": "刷新设备",
        "settings": "设置",
        "showMainWindow": "显示主窗口",
        "sound": "声音",
        "spatialAudio": "空间音频",
        "spatialAudioModes": "空间音频模式",
        "spatialSound": "空间音效",
        "switchDevice": "切换",
        "takeControl": "接管",
        "unknown": "未知",
        "unsupportedDevice": "暂不支持",
        "wearDetection": "佩戴检测",

        "anc.adaptive": "自适应",
        "anc.deep": "深度",
        "anc.light": "轻度",
        "anc.medium": "中度",
        "anc.off": "关闭",
        "anc.smart": "降噪",
        "anc.transparency": "通透",
        "component.case": "充电盒",
        "component.left": "左耳",
        "component.right": "右耳",
        "phase.connected": "已连接",
        "phase.connecting": "连接中",
        "phase.disconnected": "未连接",
        "phase.failed": "需要处理",
        "spatial.fixed": "固定",
        "spatial.off": "关闭",
        "spatial.tracking": "头部追踪",
        "status.disconnected": "已断开。",
        "status.initial": "请先在 macOS 蓝牙设置中配对 OPPO、OnePlus 或 realme 耳机，然后连接。",
        "status.searching": "正在查找支持的已配对设备...",
        "wear.disconnected": "已断连",
        "wear.inCase": "入盒",
        "wear.removed": "摘下",
        "wear.unknown": "未知",
        "wear.worn": "佩戴"
    ]
}
